---
- name: Install Vector
  hosts: vector
  become: true

  vars:
    vector_version: "0.23.0"
    vector_install_dir: "/opt/vector"

  handlers:
    - name: restart vector
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Download Vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "/tmp/vector-{{ vector_version }}.tar.gz"
        mode: '0644'

    - name: Create Vector directory
      ansible.builtin.file:
        path: "{{ vector_install_dir }}"
        state: directory
        mode: '0755'

    - name: Extract Vector
      ansible.builtin.unarchive:
        src: "/tmp/vector-{{ vector_version }}.tar.gz"
        dest: "{{ vector_install_dir }}"
        remote_src: yes
        extra_opts: ["--strip-components=2"]
        creates: "{{ vector_install_dir }}/bin/vector"

    - name: Install Vector binary
      ansible.builtin.copy:
        src: "{{ vector_install_dir }}/bin/vector"
        dest: /usr/bin/vector
        mode: '0755'
        remote_src: yes

    - name: Create Vector config directory
      ansible.builtin.file:
        path: /etc/vector
        state: directory
        mode: '0755'

    - name: Deploy Vector config
      ansible.builtin.template:
        src: vector.yaml.j2
        dest: /etc/vector/vector.yaml
        mode: '0644'
      notify: restart vector

    - name: Create systemd service for Vector
      ansible.builtin.template:
        src: vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: '0644'
      notify: restart vector

    - name: Start Vector service
      ansible.builtin.service:
        name: vector
        state: started
        enabled: yes
